//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunClient.PunWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pun", Namespace="http://puns.org/")]
    [System.SerializableAttribute()]
    public partial class Pun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PunIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JokeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PunId {
            get {
                return this.PunIdField;
            }
            set {
                if ((this.PunIdField.Equals(value) != true)) {
                    this.PunIdField = value;
                    this.RaisePropertyChanged("PunId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Joke {
            get {
                return this.JokeField;
            }
            set {
                if ((object.ReferenceEquals(this.JokeField, value) != true)) {
                    this.JokeField = value;
                    this.RaisePropertyChanged("Joke");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Pun Service v1.0Soap", Namespace="http://puns.org/", ConfigurationName="PunWebService.PunServicev10Soap")]
    public interface PunServicev10Soap {
        
        // CODEGEN: Generating message contract since element name GetPunsResult from namespace http://puns.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/GetPuns", ReplyAction="*")]
        PunClient.PunWebService.GetPunsResponse GetPuns(PunClient.PunWebService.GetPunsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/GetPuns", ReplyAction="*")]
        System.Threading.Tasks.Task<PunClient.PunWebService.GetPunsResponse> GetPunsAsync(PunClient.PunWebService.GetPunsRequest request);
        
        // CODEGEN: Generating message contract since element name GetPunByIdResult from namespace http://puns.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/GetPunById", ReplyAction="*")]
        PunClient.PunWebService.GetPunByIdResponse GetPunById(PunClient.PunWebService.GetPunByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/GetPunById", ReplyAction="*")]
        System.Threading.Tasks.Task<PunClient.PunWebService.GetPunByIdResponse> GetPunByIdAsync(PunClient.PunWebService.GetPunByIdRequest request);
        
        // CODEGEN: Generating message contract since element name pun from namespace http://puns.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/CreatePun", ReplyAction="*")]
        PunClient.PunWebService.CreatePunResponse CreatePun(PunClient.PunWebService.CreatePunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/CreatePun", ReplyAction="*")]
        System.Threading.Tasks.Task<PunClient.PunWebService.CreatePunResponse> CreatePunAsync(PunClient.PunWebService.CreatePunRequest request);
        
        // CODEGEN: Generating message contract since element name pun from namespace http://puns.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/EditPun", ReplyAction="*")]
        PunClient.PunWebService.EditPunResponse EditPun(PunClient.PunWebService.EditPunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/EditPun", ReplyAction="*")]
        System.Threading.Tasks.Task<PunClient.PunWebService.EditPunResponse> EditPunAsync(PunClient.PunWebService.EditPunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/DeletePun", ReplyAction="*")]
        void DeletePun(int punId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puns.org/DeletePun", ReplyAction="*")]
        System.Threading.Tasks.Task DeletePunAsync(int punId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPunsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPuns", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.GetPunsRequestBody Body;
        
        public GetPunsRequest() {
        }
        
        public GetPunsRequest(PunClient.PunWebService.GetPunsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPunsRequestBody {
        
        public GetPunsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPunsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPunsResponse", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.GetPunsResponseBody Body;
        
        public GetPunsResponse() {
        }
        
        public GetPunsResponse(PunClient.PunWebService.GetPunsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puns.org/")]
    public partial class GetPunsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PunClient.PunWebService.Pun[] GetPunsResult;
        
        public GetPunsResponseBody() {
        }
        
        public GetPunsResponseBody(PunClient.PunWebService.Pun[] GetPunsResult) {
            this.GetPunsResult = GetPunsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPunByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPunById", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.GetPunByIdRequestBody Body;
        
        public GetPunByIdRequest() {
        }
        
        public GetPunByIdRequest(PunClient.PunWebService.GetPunByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puns.org/")]
    public partial class GetPunByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int punId;
        
        public GetPunByIdRequestBody() {
        }
        
        public GetPunByIdRequestBody(int punId) {
            this.punId = punId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPunByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPunByIdResponse", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.GetPunByIdResponseBody Body;
        
        public GetPunByIdResponse() {
        }
        
        public GetPunByIdResponse(PunClient.PunWebService.GetPunByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puns.org/")]
    public partial class GetPunByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PunClient.PunWebService.Pun GetPunByIdResult;
        
        public GetPunByIdResponseBody() {
        }
        
        public GetPunByIdResponseBody(PunClient.PunWebService.Pun GetPunByIdResult) {
            this.GetPunByIdResult = GetPunByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePun", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.CreatePunRequestBody Body;
        
        public CreatePunRequest() {
        }
        
        public CreatePunRequest(PunClient.PunWebService.CreatePunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puns.org/")]
    public partial class CreatePunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PunClient.PunWebService.Pun pun;
        
        public CreatePunRequestBody() {
        }
        
        public CreatePunRequestBody(PunClient.PunWebService.Pun pun) {
            this.pun = pun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePunResponse", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.CreatePunResponseBody Body;
        
        public CreatePunResponse() {
        }
        
        public CreatePunResponse(PunClient.PunWebService.CreatePunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreatePunResponseBody {
        
        public CreatePunResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPun", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.EditPunRequestBody Body;
        
        public EditPunRequest() {
        }
        
        public EditPunRequest(PunClient.PunWebService.EditPunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puns.org/")]
    public partial class EditPunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PunClient.PunWebService.Pun pun;
        
        public EditPunRequestBody() {
        }
        
        public EditPunRequestBody(PunClient.PunWebService.Pun pun) {
            this.pun = pun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPunResponse", Namespace="http://puns.org/", Order=0)]
        public PunClient.PunWebService.EditPunResponseBody Body;
        
        public EditPunResponse() {
        }
        
        public EditPunResponse(PunClient.PunWebService.EditPunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditPunResponseBody {
        
        public EditPunResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PunServicev10SoapChannel : PunClient.PunWebService.PunServicev10Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PunServicev10SoapClient : System.ServiceModel.ClientBase<PunClient.PunWebService.PunServicev10Soap>, PunClient.PunWebService.PunServicev10Soap {
        
        public PunServicev10SoapClient() {
        }
        
        public PunServicev10SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PunServicev10SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PunServicev10SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PunServicev10SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PunClient.PunWebService.GetPunsResponse PunClient.PunWebService.PunServicev10Soap.GetPuns(PunClient.PunWebService.GetPunsRequest request) {
            return base.Channel.GetPuns(request);
        }
        
        public PunClient.PunWebService.Pun[] GetPuns() {
            PunClient.PunWebService.GetPunsRequest inValue = new PunClient.PunWebService.GetPunsRequest();
            inValue.Body = new PunClient.PunWebService.GetPunsRequestBody();
            PunClient.PunWebService.GetPunsResponse retVal = ((PunClient.PunWebService.PunServicev10Soap)(this)).GetPuns(inValue);
            return retVal.Body.GetPunsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PunClient.PunWebService.GetPunsResponse> PunClient.PunWebService.PunServicev10Soap.GetPunsAsync(PunClient.PunWebService.GetPunsRequest request) {
            return base.Channel.GetPunsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PunClient.PunWebService.GetPunsResponse> GetPunsAsync() {
            PunClient.PunWebService.GetPunsRequest inValue = new PunClient.PunWebService.GetPunsRequest();
            inValue.Body = new PunClient.PunWebService.GetPunsRequestBody();
            return ((PunClient.PunWebService.PunServicev10Soap)(this)).GetPunsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PunClient.PunWebService.GetPunByIdResponse PunClient.PunWebService.PunServicev10Soap.GetPunById(PunClient.PunWebService.GetPunByIdRequest request) {
            return base.Channel.GetPunById(request);
        }
        
        public PunClient.PunWebService.Pun GetPunById(int punId) {
            PunClient.PunWebService.GetPunByIdRequest inValue = new PunClient.PunWebService.GetPunByIdRequest();
            inValue.Body = new PunClient.PunWebService.GetPunByIdRequestBody();
            inValue.Body.punId = punId;
            PunClient.PunWebService.GetPunByIdResponse retVal = ((PunClient.PunWebService.PunServicev10Soap)(this)).GetPunById(inValue);
            return retVal.Body.GetPunByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PunClient.PunWebService.GetPunByIdResponse> PunClient.PunWebService.PunServicev10Soap.GetPunByIdAsync(PunClient.PunWebService.GetPunByIdRequest request) {
            return base.Channel.GetPunByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PunClient.PunWebService.GetPunByIdResponse> GetPunByIdAsync(int punId) {
            PunClient.PunWebService.GetPunByIdRequest inValue = new PunClient.PunWebService.GetPunByIdRequest();
            inValue.Body = new PunClient.PunWebService.GetPunByIdRequestBody();
            inValue.Body.punId = punId;
            return ((PunClient.PunWebService.PunServicev10Soap)(this)).GetPunByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PunClient.PunWebService.CreatePunResponse PunClient.PunWebService.PunServicev10Soap.CreatePun(PunClient.PunWebService.CreatePunRequest request) {
            return base.Channel.CreatePun(request);
        }
        
        public void CreatePun(PunClient.PunWebService.Pun pun) {
            PunClient.PunWebService.CreatePunRequest inValue = new PunClient.PunWebService.CreatePunRequest();
            inValue.Body = new PunClient.PunWebService.CreatePunRequestBody();
            inValue.Body.pun = pun;
            PunClient.PunWebService.CreatePunResponse retVal = ((PunClient.PunWebService.PunServicev10Soap)(this)).CreatePun(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PunClient.PunWebService.CreatePunResponse> PunClient.PunWebService.PunServicev10Soap.CreatePunAsync(PunClient.PunWebService.CreatePunRequest request) {
            return base.Channel.CreatePunAsync(request);
        }
        
        public System.Threading.Tasks.Task<PunClient.PunWebService.CreatePunResponse> CreatePunAsync(PunClient.PunWebService.Pun pun) {
            PunClient.PunWebService.CreatePunRequest inValue = new PunClient.PunWebService.CreatePunRequest();
            inValue.Body = new PunClient.PunWebService.CreatePunRequestBody();
            inValue.Body.pun = pun;
            return ((PunClient.PunWebService.PunServicev10Soap)(this)).CreatePunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PunClient.PunWebService.EditPunResponse PunClient.PunWebService.PunServicev10Soap.EditPun(PunClient.PunWebService.EditPunRequest request) {
            return base.Channel.EditPun(request);
        }
        
        public void EditPun(PunClient.PunWebService.Pun pun) {
            PunClient.PunWebService.EditPunRequest inValue = new PunClient.PunWebService.EditPunRequest();
            inValue.Body = new PunClient.PunWebService.EditPunRequestBody();
            inValue.Body.pun = pun;
            PunClient.PunWebService.EditPunResponse retVal = ((PunClient.PunWebService.PunServicev10Soap)(this)).EditPun(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PunClient.PunWebService.EditPunResponse> PunClient.PunWebService.PunServicev10Soap.EditPunAsync(PunClient.PunWebService.EditPunRequest request) {
            return base.Channel.EditPunAsync(request);
        }
        
        public System.Threading.Tasks.Task<PunClient.PunWebService.EditPunResponse> EditPunAsync(PunClient.PunWebService.Pun pun) {
            PunClient.PunWebService.EditPunRequest inValue = new PunClient.PunWebService.EditPunRequest();
            inValue.Body = new PunClient.PunWebService.EditPunRequestBody();
            inValue.Body.pun = pun;
            return ((PunClient.PunWebService.PunServicev10Soap)(this)).EditPunAsync(inValue);
        }
        
        public void DeletePun(int punId) {
            base.Channel.DeletePun(punId);
        }
        
        public System.Threading.Tasks.Task DeletePunAsync(int punId) {
            return base.Channel.DeletePunAsync(punId);
        }
    }
}
